from pathlib import Path
import tempfile
import unittest

import numpy as np
from ase import Atoms

from orca_viz.cube import (
    CubeData,
    cube_phase_visibility,
    parse_cube_file,
    suggest_cube_isovalue,
    suggest_cube_level_max,
    suggest_cube_level_min,
)
from orca_viz.i18n import set_language
from orca_viz.visualization import _cube_render_budget, create_cube_isosurface_figure


def _write_demo_cube(path: Path, title: str) -> None:
    path.write_text(
        "\n".join(
            [
                "Cube data generated by ORCA",
                title,
                "    2    0.000000    0.000000    0.000000",
                "    2    1.000000    0.000000    0.000000",
                "    2    0.000000    1.000000    0.000000",
                "    2    0.000000    0.000000    1.000000",
                "    6    6.000000    0.000000    0.000000    0.000000",
                "    1    1.000000    1.800000    0.000000    0.000000",
                "  0.100000 -0.050000  0.050000 -0.100000  0.120000 -0.120000",
                "  0.080000 -0.080000",
            ]
        )
    )


class CubeTests(unittest.TestCase):
    def tearDown(self) -> None:
        set_language("zh")

    def test_cube_kind_inference(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            esp_path = root / "demo.scfp.esp.cube"
            mo_path = root / "demo.mo36a.cube"
            _write_demo_cube(esp_path, "Electrostatic Potential")
            _write_demo_cube(mo_path, "Molecular orbital 36 of operator 0")

            esp_cube = parse_cube_file(esp_path)
            mo_cube = parse_cube_file(mo_path)

            self.assertEqual(esp_cube.metadata["cube_kind"], "esp")
            self.assertEqual(mo_cube.metadata["cube_kind"], "orbital")

    def test_suggest_cube_isovalue_and_render(self) -> None:
        cube = CubeData(
            source_name="demo.mo36a.cube",
            atoms=Atoms(symbols=["C", "H"], positions=[(0, 0, 0), (1.1, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(3, 3, 3),
            values=np.array(
                [
                    [[0.00, 0.01, -0.03], [0.02, -0.04, 0.06], [0.01, -0.01, 0.00]],
                    [[0.00, -0.02, 0.05], [0.08, -0.10, 0.12], [0.02, -0.03, 0.01]],
                    [[0.00, 0.01, -0.02], [0.03, -0.05, 0.07], [0.01, -0.02, 0.00]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Molecular orbital 36 of operator 0"),
            metadata={"cube_kind": "orbital", "cube_kind_label": "分子轨道"},
        )

        level = suggest_cube_isovalue(cube)
        self.assertGreater(level, 0)
        self.assertLess(level, 0.03)
        self.assertLess(suggest_cube_level_min(cube), level)

        figure = create_cube_isosurface_figure(cube, level=level, quality="精细")
        trace_names = [trace.name for trace in figure.data if getattr(trace, "name", None)]
        self.assertIn("phase +", trace_names)
        self.assertIn("phase -", trace_names)
        self.assertIsNotNone(figure.layout.scene.xaxis.range)
        self.assertIsNotNone(figure.layout.scene.yaxis.range)
        self.assertIsNotNone(figure.layout.scene.zaxis.range)

    def test_esp_level_is_robust_to_positive_spikes(self) -> None:
        cube = CubeData(
            source_name="demo.scfp.esp.cube",
            atoms=Atoms(symbols=["C", "H"], positions=[(0, 0, 0), (1.1, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(3, 3, 3),
            values=np.array(
                [
                    [[0.002, 0.004, -0.010], [0.006, -0.018, 0.012], [0.005, -0.007, 0.003]],
                    [[0.004, -0.012, 0.020], [0.030, -0.028, 8.000], [0.008, -0.010, 0.006]],
                    [[0.003, 0.006, -0.015], [0.009, -0.020, 0.015], [0.004, -0.008, 0.002]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Electrostatic Potential"),
            metadata={"cube_kind": "esp", "cube_kind_label": "ESP 静电势"},
        )

        level = suggest_cube_isovalue(cube)
        level_max = suggest_cube_level_max(cube)
        figure = create_cube_isosurface_figure(cube, level=level, quality="精细", opacity=0.2)
        trace_names = [trace.name for trace in figure.data if getattr(trace, "name", None)]

        self.assertLess(level, 0.1)
        self.assertLess(level_max, float(np.max(np.abs(cube.values))))
        self.assertGreater(level_max, level)
        self.assertIn("ESP > 0", trace_names)
        self.assertIn("ESP < 0", trace_names)

    def test_electron_density_default_level_stays_in_outer_surface_range(self) -> None:
        cube = CubeData(
            source_name="demo.eldens.cube",
            atoms=Atoms(symbols=["C", "H"], positions=[(0, 0, 0), (1.1, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(4, 4, 4),
            values=np.array(
                [
                    [[1e-8, 2e-7, 1e-6, 4e-6], [3e-7, 4e-6, 2e-5, 8e-5], [7e-6, 3e-5, 4e-4, 2e-3], [8e-6, 7e-5, 5e-4, 2e-3]],
                    [[2e-7, 4e-6, 3e-5, 1.2e-4], [5e-6, 6e-5, 9e-4, 4e-3], [4e-5, 8e-4, 5e-3, 2e-2], [7e-5, 1.0e-3, 8e-3, 4e-2]],
                    [[4e-7, 7e-6, 7e-5, 2e-4], [7e-6, 1.0e-4, 1.5e-3, 6e-3], [5e-5, 1.2e-3, 9e-3, 4e-2], [7e-5, 1.1e-3, 8e-3, 3e-2]],
                    [[2e-7, 4e-6, 3e-5, 1.0e-4], [4e-6, 6e-5, 8e-4, 3e-3], [2e-5, 6e-4, 5e-3, 1.8e-2], [3e-5, 8e-4, 6e-3, 2.5e-2]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Electron density"),
            metadata={"cube_kind": "electron_density", "cube_kind_label": "电子密度"},
        )

        level = suggest_cube_isovalue(cube)
        self.assertGreater(level, 0.0005)
        self.assertLess(level, 0.01)

    def test_spin_density_renders_positive_and_negative_surfaces(self) -> None:
        cube = CubeData(
            source_name="demo.spindens.cube",
            atoms=Atoms(symbols=["N"], positions=[(0, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(3, 3, 3),
            values=np.array(
                [
                    [[0.0, 0.01, -0.02], [0.02, -0.03, 0.04], [0.01, -0.01, 0.0]],
                    [[0.0, -0.02, 0.03], [0.05, -0.07, 0.09], [0.02, -0.02, 0.01]],
                    [[0.0, 0.01, -0.02], [0.02, -0.03, 0.04], [0.01, -0.01, 0.0]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Spin density"),
            metadata={"cube_kind": "spin_density", "cube_kind_label": "自旋密度"},
        )

        figure = create_cube_isosurface_figure(cube, level=0.02, quality="精细")
        trace_names = [trace.name for trace in figure.data if getattr(trace, "name", None)]
        self.assertIn("spin +", trace_names)
        self.assertIn("spin -", trace_names)

    def test_esp_density_surface_mode_builds_mesh(self) -> None:
        density_values = np.zeros((6, 6, 6), dtype=float)
        esp_values = np.zeros((6, 6, 6), dtype=float)
        center = np.array([2.5, 2.5, 2.5])
        for i in range(6):
            for j in range(6):
                for k in range(6):
                    offset = np.array([i, j, k], dtype=float) - center
                    radius = np.linalg.norm(offset)
                    density_values[i, j, k] = np.exp(-(radius**2) / 3.2)
                    esp_values[i, j, k] = offset[0] * 0.08

        esp_cube = CubeData(
            source_name="demo.scfp.esp.cube",
            atoms=Atoms(symbols=["C"], positions=[(2.5, 2.5, 2.5)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(6, 6, 6),
            values=esp_values,
            comments=("Cube data generated by ORCA", "Electrostatic Potential"),
            metadata={"cube_kind": "esp", "cube_kind_label": "ESP 静电势"},
        )
        density_cube = CubeData(
            source_name="demo.eldens.cube",
            atoms=Atoms(symbols=["C"], positions=[(2.5, 2.5, 2.5)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(6, 6, 6),
            values=density_values,
            comments=("Cube data generated by ORCA", "Electron density"),
            metadata={"cube_kind": "electron_density", "cube_kind_label": "电子密度"},
        )

        figure = create_cube_isosurface_figure(
            esp_cube,
            level=0.2,
            quality="极致",
            surface_mode="density_surface",
            surface_cube=density_cube,
        )
        self.assertTrue(any(trace.type == "mesh3d" for trace in figure.data))

    def test_phase_visibility_reports_single_phase(self) -> None:
        cube = CubeData(
            source_name="demo.mo1a.cube",
            atoms=Atoms(symbols=["C"], positions=[(0, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(2, 2, 2),
            values=np.array(
                [
                    [[0.001, 0.002], [0.003, 0.004]],
                    [[-0.002, -0.003], [0.002, 0.001]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Molecular orbital 1 of operator 0"),
            metadata={"cube_kind": "orbital", "cube_kind_label": "分子轨道"},
        )
        visibility = cube_phase_visibility(cube, level=0.0035)
        self.assertTrue(visibility["single_phase"])
        self.assertTrue(visibility["positive"])
        self.assertFalse(visibility["negative"])

    def test_render_budget_accepts_english_quality_labels(self) -> None:
        self.assertEqual(_cube_render_budget("orbital", "Ultra"), 972000)


if __name__ == "__main__":
    unittest.main()
