from pathlib import Path
import tempfile
import unittest

import numpy as np
from ase import Atoms

from orca_viz.cube import CubeData, parse_cube_file, suggest_cube_isovalue, suggest_cube_level_max
from orca_viz.i18n import set_language
from orca_viz.visualization import _cube_render_budget, create_cube_isosurface_figure


def _write_demo_cube(path: Path, title: str) -> None:
    path.write_text(
        "\n".join(
            [
                "Cube data generated by ORCA",
                title,
                "    2    0.000000    0.000000    0.000000",
                "    2    1.000000    0.000000    0.000000",
                "    2    0.000000    1.000000    0.000000",
                "    2    0.000000    0.000000    1.000000",
                "    6    6.000000    0.000000    0.000000    0.000000",
                "    1    1.000000    1.800000    0.000000    0.000000",
                "  0.100000 -0.050000  0.050000 -0.100000  0.120000 -0.120000",
                "  0.080000 -0.080000",
            ]
        )
    )


class CubeTests(unittest.TestCase):
    def tearDown(self) -> None:
        set_language("zh")

    def test_cube_kind_inference(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            esp_path = root / "demo.scfp.esp.cube"
            mo_path = root / "demo.mo36a.cube"
            _write_demo_cube(esp_path, "Electrostatic Potential")
            _write_demo_cube(mo_path, "Molecular orbital 36 of operator 0")

            esp_cube = parse_cube_file(esp_path)
            mo_cube = parse_cube_file(mo_path)

            self.assertEqual(esp_cube.metadata["cube_kind"], "esp")
            self.assertEqual(mo_cube.metadata["cube_kind"], "orbital")

    def test_suggest_cube_isovalue_and_render(self) -> None:
        cube = CubeData(
            source_name="demo.mo36a.cube",
            atoms=Atoms(symbols=["C", "H"], positions=[(0, 0, 0), (1.1, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(3, 3, 3),
            values=np.array(
                [
                    [[0.00, 0.01, -0.03], [0.02, -0.04, 0.06], [0.01, -0.01, 0.00]],
                    [[0.00, -0.02, 0.05], [0.08, -0.10, 0.12], [0.02, -0.03, 0.01]],
                    [[0.00, 0.01, -0.02], [0.03, -0.05, 0.07], [0.01, -0.02, 0.00]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Molecular orbital 36 of operator 0"),
            metadata={"cube_kind": "orbital", "cube_kind_label": "分子轨道"},
        )

        level = suggest_cube_isovalue(cube)
        self.assertGreater(level, 0)

        figure = create_cube_isosurface_figure(cube, level=level, quality="精细")
        trace_names = [trace.name for trace in figure.data if getattr(trace, "name", None)]
        self.assertIn("phase +", trace_names)
        self.assertIn("phase -", trace_names)

    def test_esp_level_is_robust_to_positive_spikes(self) -> None:
        cube = CubeData(
            source_name="demo.scfp.esp.cube",
            atoms=Atoms(symbols=["C", "H"], positions=[(0, 0, 0), (1.1, 0, 0)]),
            origin_angstrom=np.array([0.0, 0.0, 0.0]),
            axis_vectors_angstrom=np.eye(3),
            grid_shape=(3, 3, 3),
            values=np.array(
                [
                    [[0.002, 0.004, -0.010], [0.006, -0.018, 0.012], [0.005, -0.007, 0.003]],
                    [[0.004, -0.012, 0.020], [0.030, -0.028, 8.000], [0.008, -0.010, 0.006]],
                    [[0.003, 0.006, -0.015], [0.009, -0.020, 0.015], [0.004, -0.008, 0.002]],
                ]
            ),
            comments=("Cube data generated by ORCA", "Electrostatic Potential"),
            metadata={"cube_kind": "esp", "cube_kind_label": "ESP 静电势"},
        )

        level = suggest_cube_isovalue(cube)
        level_max = suggest_cube_level_max(cube)
        figure = create_cube_isosurface_figure(cube, level=level, quality="精细", opacity=0.2)
        trace_names = [trace.name for trace in figure.data if getattr(trace, "name", None)]

        self.assertLess(level, 0.1)
        self.assertLess(level_max, float(np.max(np.abs(cube.values))))
        self.assertGreater(level_max, level)
        self.assertIn("ESP > 0", trace_names)
        self.assertIn("ESP < 0", trace_names)

    def test_render_budget_accepts_english_quality_labels(self) -> None:
        self.assertEqual(_cube_render_budget("orbital", "Ultra"), 275000)


if __name__ == "__main__":
    unittest.main()
